# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  mesoftcase.webapi:
    build:
      context: "/Users/mrttlmn/RiderProjects/MeSoft-Case"
      dockerfile: "MeSoftCase.WebApi/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "mesoftcase.webapi:dev"
    ports:
    - "127.0.0.1:57008:57000"
    - "127.0.0.1:57208:57200"
    - "127.0.0.1:57408:57400"
    volumes:
    - "/Users/mrttlmn/RiderProjects/MeSoft-Case/MeSoftCase.WebApi:/app:rw"
    - "/Users/mrttlmn/RiderProjects/MeSoft-Case:/src:rw"
    - "/Users/mrttlmn/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/mrttlmn/.local/share/JetBrains/RiderRemoteDebugger/2024.3.6/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/mrttlmn/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_3_26_22_18_13:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  mesoftcase.webui:
    build:
      context: "/Users/mrttlmn/RiderProjects/MeSoft-Case"
      dockerfile: "MeSoftCase.UI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/MeSoftCase.UI.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "mesoftcase.webui:dev"
    ports:
    - "127.0.0.1:57009:57000"
    - "127.0.0.1:57209:57200"
    - "127.0.0.1:57409:57400"
    volumes:
    - "/Users/mrttlmn/RiderProjects/MeSoft-Case/MeSoftCase.UI:/app:rw"
    - "/Users/mrttlmn/RiderProjects/MeSoft-Case:/src:rw"
    - "/Users/mrttlmn/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/mrttlmn/.local/share/JetBrains/RiderRemoteDebugger/2024.3.6/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/mrttlmn/Library/Logs/JetBrains/Rider2024.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_3_26_22_18_13:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
